loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: default
    size: 50Gi

promtail:
  enabled: true
  pipelineStages:
    - cri: {}
    - json:
      expressions:
      is_even: is_even
      level: level
      version: version

grafana:
  enabled: true
  sidecar:
    datasources:
    enabled: true
  image:
    tag: 8.3.5
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - "< YOUR FQDN FOR ELB FOR NGINX GOES HERE >"